###### Main Service ######
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-auth-deployment
  template:
    metadata:
      labels:
        name: acmeair-auth-deployment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        pull-timestamp: "0"
    spec:
      containers:
      - name: acmeair-authservice-java
        image: acmeair-authservice-java:latest
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
        env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: password
        - name: JVM_ARGS
          value: "-DcustomerClient/mp-rest/url=http://acmeair-customer-service:9080/customer"
        - name: SECURE_SERVICE_CALLS
          value: 'true'
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-auth-service
spec:
  ports:
    - port: 9080
  selector:
    name: acmeair-auth-deployment
